#pragma once
#define CONFIG_FREERTOS_HZ 1000

#define CONFIG_ENV_GPIO_RANGE_MIN 0
#define CONFIG_ENV_GPIO_RANGE_MAX 48
#define CONFIG_ENV_GPIO_IN_RANGE_MAX 48
#define CONFIG_ENV_GPIO_OUT_RANGE_MAX 48
#define CONFIG_INT_IO 16
#define CONFIG_INDI_LED 1
#define CONFIG_FIRE_1 47
#define CONFIG_FIRE_2 48
#define CONFIG_I2C_MASTER_SCL 8
#define CONFIG_I2C_MASTER_SDA 9
#define CONFIG_LORA_MOSI_GPIO 35
#define CONFIG_LORA_MISO_GPIO 37
#define CONFIG_LORA_SCK_GPIO 36
#define CONFIG_LORA_NSS_GPIO 21
#define CONFIG_RST_GPIO 41
#define CONFIG_BUSY_GPIO 40
#define CONFIG_TXEN_GPIO 0
#define CONFIG_RXEN_GPIO 0
#define CONFIG_SD_MOSI_GPIO 11
#define CONFIG_SD_MISO_GPIO 13
#define CONFIG_SD_SCK_GPIO 12
#define CONFIG_SD_NSS_GPIO 10